import type { Metadata } from "next";
import {Be_Vietnam_Pro} from 'next/font/google';
import "./globals.css";

const be_vietnam = Be_Vietnam_Pro({
  weight: ['100','200','300','400','500','600','700','800','900'],
  style: 'normal',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={be_vietnam.className}>
      <body className=''>
        {children}
      </body>
    </html>
  );
};
